FROM fpga.dphi.space:5000/alpine

WORKDIR /app
COPY echo-test.sh .
COPY echo-test.sh .
COPY echo-test.sh .
COPY echo-test.sh .
COPY echo-test.sh .
RUN chmod +x /app/echo-test.sh

ENTRYPOINT [ "/app/echo-test.sh" ]
